version: "3.9"
services:
  epsilon-model:
    build: ./epsilon-backend
    image: ghcr.io/douida-othmane/compose2kubernetes-backend:1.0.0
    ports:
      - "8080:8080"
    networks:
      - mde_net
  discord-bot:
    build: ./discord-bot
    image: ghcr.io/douida-othmane/compose2kubernetes-discord:1.0.0
    ports:
      - "3000:3000"
    environment:
      - BOT_TOKEN
      - BOT_ID
      - DB_URL
      - API_URL
    networks:
      - mde_net 
    depends_on:
      - epsilon-model
networks:
  mde_net: